# Generated by Django 5.2.2 on 2025-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_intro', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
